### PR TITLE
Fix leading spaces bug in delete commands, fix incorrect UI when deleteI command is executed

### LINKED ISSUE #193: [PE-D][Tester E] Deleting an item from ingredient list causes number remaining to wrongly show using number of recipes
When I delete an ingredient from ingredient list, the message tells me number of recipes in list instead of number of ingredients in list:

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: naveen42x/ped#6

### PR DESCRIPTION
**Pull request by seanngja**
`delete` and `deleteI` now will match the recipes and ingredients to be deleted if leading spaces are inputted by the user. The UI print statements when an ingredient is deleted is also updated
Should resolve #193, #196 and #199

### CODE REVIEW

**Comment by Sukkaito** [comment]
Can you update the title and the description, it's a bit misleading (for me), because I think these are 2 different problems (leading/trailing spaces vs incorrect list used)

**Comment by seanngja** [comment]
@Sukkaito I have updated the title and description. Both of these issues were addressed in this PR, which may have caused your confusion. Apologies about that.

File: src/main/java/ymfc/ui/Ui.java [hunk 1]
```diff
@@ -204,7 +204,22 @@ public void printDeletedTask(String deletedRecipe, int listCount) {
         System.out.println("\t  " + deletedRecipe);
         // Conditional operator to pluralize "recipe" when listCount above 1
         System.out.println("\tYou currently have " + listCount +
-                (listCount <= 1 ? " recipe" : " recipes") + " in your list.");
```
Comment (Sukkaito) [inline src/main/java/ymfc/ui/Ui.java:207]: What if there is no recipe left in the list? Should this line be alright if you leave it as it is? 🤔

Comment (seanngja) [reply src/main/java/ymfc/ui/Ui.java:207]: If there is no recipe left in the list, it will print:
`You currently have: 0 recipes in your list` which I believe is more grammatically correct

Comment (Sukkaito) [reply src/main/java/ymfc/ui/Ui.java:207]: Oh you're right! I've just searched this on Google! New knowledge for me! 👍

**Review by Sukkaito — APPROVED** [review]
LGTM! Can merge anytime, or wait for another member to review. 👍

**Review by KSanjith — APPROVED** [review]
LGTM
