### PR TITLE
bugfix: Show correct logs for missing savefile

### LINKED ISSUE #115: bug: no savefile is found, yet recipes still get loaded
`recipe.txt` isn't found (at least according to the Logger), yet recipes still manage to load.
Probably a bug in the logger but still need a bit of investigating.

### Step to reproduce:
- Make sure you have a savefile with valid recipes in `./data`
- Run the program

### Expected results:
- Savefile is found, recipes are loaded successfully

### Actual results:
- Savefile is NOT found, recipe are still loaded successfully
- Figure 1: Run within Inteliji
- Figure 2: Run separately from `.jar`
image
image

### PR DESCRIPTION
**Pull request by Sukkaito**
Resolve #115

### CODE REVIEW

File: src/main/java/ymfc/storage/Storage.java [hunk 1]
```diff
@@ -78,12 +80,18 @@ public void saveIngredients(IngredientList ingredients) throws IOException {
...
+                            Ui ui, Storage storage) {
+        Scanner reader;
+        try {
+            File tasksFile = new File(saveRecipeFilePath);
+            reader = new Scanner(tasksFile);
+        } catch (FileNotFoundException exception) {
+            logger.log(Level.INFO, "No recipes savefile found");
+            return;
+        }
+
```
Comment (KSanjith) [inline src/main/java/ymfc/storage/Storage.java:94]: Splitting the log messages to the individual recipe and ingredient load methods makes more sense and fixes the bug. Nice work.

**Review by KSanjith — COMMENTED** [review]
LGTM
